apiVersion: v1
kind: ConfigMap
metadata:
  name: flame-default-realm
  namespace: {{ .Release.Namespace }}
data:
  flame.json: |
    {
      "realm" : "flame",
      "defaultSignatureAlgorithm" : "RS256",
      "accessTokenLifespan" : 7200,
      "enabled" : true,
      "requiredCredentials" : [ "password" ],
      "users" : [ {
        "username" : "service-account-service1",
        "emailVerified" : false,
        "enabled" : true,
        "totp" : false,
        "serviceAccountClientId" : "service1",
        "credentials" : [ ],
        "disableableCredentialTypes" : [ ],
        "requiredActions" : [ ],
        "realmRoles" : [ "default-roles-flame" ],
        "clientRoles" : {
          "realm-management" : [
            "create-client",
            "manage-clients",
            "view-events",
            "query-clients"
          ],
          "service1" : [ "uma_protection" ]
        },
        "notBefore" : 0,
        "groups" : [ ]
      } ],
      "clients" : [ {
        "clientId" : "hub-adapter",
        "name" : "Node Hub Adapter Gateway API",
        "description" : "",
        "rootUrl" : "",
        "adminUrl" : "",
        "baseUrl" : "",
        "surrogateAuthRequired" : false,
        "enabled" : true,
        "alwaysDisplayInConsole" : false,
        "clientAuthenticatorType" : "client-secret",
        "secret" : "${hubAdapterClientSecret}",
        "redirectUris" : [ "/*" ],
        "webOrigins" : [ "/*" ],
        "notBefore" : 0,
        "bearerOnly" : false,
        "consentRequired" : false,
        "standardFlowEnabled" : true,
        "implicitFlowEnabled" : false,
        "directAccessGrantsEnabled" : true,
        "serviceAccountsEnabled" : true,
        "publicClient" : false
      }, {
        "clientId" : "service1",
        "name" : "Test service",
        "description" : "",
        "rootUrl" : "",
        "adminUrl" : "",
        "baseUrl" : "",
        "surrogateAuthRequired" : false,
        "enabled" : true,
        "alwaysDisplayInConsole" : false,
        "clientAuthenticatorType" : "client-secret",
        "secret" : "${podOrcClientSecret}",
        "redirectUris" : [ "/*" ],
        "webOrigins" : [ "/*" ],
        "notBefore" : 0,
        "bearerOnly" : false,
        "consentRequired" : false,
        "standardFlowEnabled" : true,
        "implicitFlowEnabled" : false,
        "directAccessGrantsEnabled" : true,
        "serviceAccountsEnabled" : true,
        "publicClient" : false
      } ]
    }
