{{- $hasCerts := include "tls.hasCerts" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-po
  labels:
    component: flame-po
    app.kubernetes.io/name: flame-po
    app.kubernetes.io/component: orchestrator
    app.kubernetes.io/part-of: flame-node
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      component: flame-po
      app.kubernetes.io/name: flame-po
      app.kubernetes.io/component: orchestrator
      app.kubernetes.io/part-of: flame-node
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.hubAdapter.replicaCount }}
  template:
    metadata:
      annotations:
        {{- with .Values.podOrchestrator.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        component: flame-po
        app.kubernetes.io/name: flame-po
        app.kubernetes.io/component: orchestrator
        app.kubernetes.io/part-of: flame-node
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.podOrchestrator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.podOrchestrator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podOrchestrator.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ .Release.Name }}-po-sa
      #automountServiceAccountToken: false
      initContainers:
        - name: init-postgres
          securityContext:
            {{- toYaml .Values.podOrchestrator.waitForPostgres.securityContext | nindent 12 }}
          image: "{{ .Values.podOrchestrator.waitForPostgres.image.repository }}:{{ .Values.podOrchestrator.waitForPostgres.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.podOrchestrator.waitForPostgres.image.pullPolicy }}
          command: ['sh', '-c', "until nc -vz {{ include "postgresql.endpoint" . }}.{{ .Release.Namespace }}.svc {{ .Values.postgresql.service.port }}; do echo waiting for postgres; sleep 2; done"]
          {{- with .Values.podOrchestrator.waitForPostgres.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.podOrchestrator.waitForPostgres.resources | nindent 12 }}
      containers:
        - name: po
          securityContext:
            {{- toYaml .Values.podOrchestrator.securityContext | nindent 12 }}
          image: "{{ .Values.podOrchestrator.image.repository }}:{{ .Values.podOrchestrator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.podOrchestrator.image.pullPolicy }}
          #image: po:latest
          #imagePullPolicy: IfNotPresent
          #VolumeMounts:
          #  - mountPath: /config/keys
          #    name: keys
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: {{ .Values.timezone | default "Europe/Berlin" }}
            - name: POSTGRES_HOST
              value: {{ include "postgresql.endpoint" . }}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.user.secretName" . }}
                  key: DB_DATABASE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.user.secretName" . }}
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.user.secretName" . }}
                  key: DB_PASSWORD
            - name: PO_HTTP_PROXY
              value: {{ .Values.proxy.httpProxy | default "" }}
            - name: PO_HTTPS_PROXY
              value: {{ .Values.proxy.httpsProxy | default "" }}
            - name: RESULT_CLIENT_ID
              value: "service1"
            - name: RESULT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-keycloak-client-secrets
                  key: podOrcClientSecret
            - name: KEYCLOAK_URL
              value: {{ include "keycloak.base.endpoint" . }}
            - name: KEYCLOAK_REALM
              value: "flame"
            - name: HUB_URL_AUTH
              value: {{ .Values.hub.endpoints.auth | default "https://auth.privateaim.dev" | quote }}
            - name: HUB_URL_CORE
              value: {{ .Values.hub.endpoints.core | default "https://core.privateaim.dev" | quote }}
            - name: HUB_ROBOT_USER
              value:  {{ required "A robot ID for the Hub is required." .Values.hub.auth.robotUser | quote }}
            - name: HUB_ROBOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "hub.secretName" . }}
                  key: robotSecret
            - name: HUB_LOGGING
              value: {{ .Values.podOrchestrator.enableHubLogging | default "True" | quote }}
            - name: STATUS_LOOP_INTERVAL
              value:  {{ .Values.podOrchestrator.statusLoopInterval | default "10" | quote }}
            {{- if $hasCerts }}
            - name: EXTRA_CA_CERTS
              value: "/mnt/certs/certs.pem"
            {{- end }}
            {{- with .Values.podOrchestrator.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.podOrchestrator.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.podOrchestrator.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.podOrchestrator.resources | nindent 12 }}
          volumeMounts:
            {{- if $hasCerts }}
            - mountPath: "/mnt/certs/certs.pem"
              name: additional-certs
              subPath: "certs.pem"
              readOnly: true
            {{- end }}
            {{- with .Values.podOrchestrator.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if $hasCerts }}
        - name: additional-certs
          configMap:
            name: {{ include "tls.configMapName" . }}
        {{- end }}
        {{- with .Values.podOrchestrator.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.podOrchestrator.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.podOrchestrator.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.podOrchestrator.tolerations | nindent 8 }}
