blaze:
  nameOverride: node-datastore-blaze
  fullnameOverride: node-datastore-blaze

minio:
  nameOverride: node-datastore-minio
  fullnameOverride: node-datastore-minio

  serviceAccount:
    create: true
    name: node-datastore-minio-sa
  
  rootUser: ""
  rootPassword: ""

  ## Use existing Secret that store following variables:
  ##
  ## | Chart var    | .data.<key> in Secret |
  ## |:-------------|:----------------------|
  ## | rootUser     | rootUser              |
  ## | rootPassword | rootPassword          |
  ##
  ## When set, rootUser and rootPassword above are ignored.
  existingSecret: ""

  mode: standalone
  replicas: 1
  resources:
    requests:
      memory: 1Gi

  persistence:
    enabled: true
    size: 5Gi