{{- $hasProxyAuth := include "broker.proxy.hasAuth" . -}}
{{- $hasCerts := include "tls.hasCerts" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-node-message-broker
  labels:
    component: flame-message-broker
    app.kubernetes.io/name: flame-message-broker
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: flame-node
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.messageBroker.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      component: flame-message-broker
      app.kubernetes.io/name: flame-message-broker
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: flame-node
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- with .Values.messageBroker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        component: flame-message-broker
        app.kubernetes.io/name: flame-message-broker
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: flame-node
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.messageBroker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.messageBroker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.messageBroker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-node-message-broker
          image: "{{ .Values.messageBroker.image.repository }}:{{ .Values.messageBroker.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.messageBroker.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.messageBroker.securityContext | nindent 12 }}
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: {{ .Values.timezone | default "Europe/Berlin" }}
            - name: AUTH_JWKS_URL
              value: {{ required "A valid JWKS URL for Keycloak is required." (include "keycloak.jwks.endpoint" .) }}
            - name: HUB_AUTH_BASE_URL
              value: {{ required "A valid HUB Auth base URL is required." .Values.hub.endpoints.auth | default "https://auth.privateaim.net/" | quote }}
            - name: HUB_AUTH_CLIENT_ID
              value: {{ required "A client ID for the Hub is required." .Values.hub.auth.clientID | quote }}
            - name: HUB_AUTH_CLIENT_SECRET_FILE
              value: "/opt/message-broker/auth/client_secret.txt"
            - name: HUB_BASE_URL
              value: {{ required "A valid HUB API base URL is required." .Values.hub.endpoints.core | default "https://api.privateaim.net/" | quote}}
            - name: HUB_MESSENGER_BASE_URL
              value: {{ required "A valid HUB Messenger base URL is required." .Values.hub.endpoints.messenger | default "https://messenger.privateaim.net/" | quote }}
            - name: PERSISTENCE_DATABASE_NAME
              value: "message-broker"
            - name: PERSISTENCE_HOSTNAME
              value: {{ .Release.Name }}-mongodb
            - name: PERSISTENCE_PORT
              value: "27017"
            {{- if or .Values.proxy.httpProxy .Values.proxy.httpsProxy }}
            - name: PROXY_HOST
              value: {{ include "broker.proxy.host" . | default "" | quote }}
            - name: PROXY_PORT
              value: {{ include "broker.proxy.port" . | default "" | quote }}
            - name: PROXY_WHITELIST
              value: "^.*nginx-analysis.*$"
            {{- end }}
            {{- if $hasProxyAuth }}
            - name: PROXY_USERNAME
              value: {{ include "broker.proxy.username" . | default "" | quote }}
            - name: PROXY_PASSWORD_FILE
              value: "/opt/message-broker/proxy/proxy_password.txt"
            {{- end }}
            - name: SECURITY_NODE_PRIVATE_ECDH_KEY_FILE
              value: "/opt/message-broker/crypto/private_key.pem"
            - name: SERVER_PORT
              value: "8080"
            {{- if $hasCerts }}
            - name: SECURITY_ADDITIONAL_TRUSTED_CERTS_FILE
              value: "/mnt/certs/certs.pem"
            {{- end }}
            {{- with .Values.messageBroker.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.messageBroker.resources | nindent 12 }}
          {{- with .Values.messageBroker.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.messageBroker.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: "/opt/message-broker/crypto/private_key.pem"
              name: "crypto"
              subPath: "private_key.pem"
              readOnly: true
            {{- if $hasCerts }}
            - mountPath: "/mnt/certs/certs.pem"
              name: additional-certs
              subPath: "certs.pem"
              readOnly: true
            {{- end }}
            - mountPath: "/opt/message-broker/auth/client_secret.txt"
              name: "auth"
              subPath: "client_secret.txt"
              readOnly: true
            {{- if $hasProxyAuth }}
            - mountPath: "/opt/message-broker/proxy/proxy_password.txt"
              name: "proxy"
              subPath: "proxy_password.txt"
              readOnly: true
            {{- end }}
            {{- with .Values.messageBroker.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: crypto
          secret:
            secretName: {{ include "hub.crypto.privateKeySecretName" . }}
            items:
              - key: "private_key.pem"
                path: "private_key.pem"
        {{- if $hasCerts }}
        - name: additional-certs
          configMap:
            name: {{ include "tls.configMapName" . }}
        {{- end }}
        - name: auth
          secret:
            secretName: {{ include "hub.secretName" . }}
            items:
              - key: clientSecret
                path: "client_secret.txt"
        {{- if $hasProxyAuth }}
        - name: proxy
          secret:
            secretName: {{ .Release.Name }}-proxy-credentials-secret
            items:
              - key: proxyPassword
                path: "proxy_password.txt"
        {{- end }}
        {{- with .Values.messageBroker.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.messageBroker.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.messageBroker.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.messageBroker.tolerations | nindent 8 }}
