global:
    imagePullPolicy: "Always"

    redis:
        password: "start123"

    flameHub:
        ingress:
            enabled: true
            ssl: false
            hostname: "localhost"

image:
    registry: ghcr.io
    repository: privateaim/hub
    tag: latest

# internal services
clientUI:
    cookieDomain: ""
    ingress:
        enabled: false
        hostname: ""
        path: "/"
        pathType: "Prefix"

authup:
    ingress:
        hostname: ""
        ssl: false

serverCore:
    ingress:
        ssl: false
        enabled: false
        hostname: ""
        path: "/"
        pathType: "Prefix"
    env:
        masterImagesBranch: ""

serverMessenger:
    ingress:
        ssl: false
        enabled: false
        hostname: ""
        path: "/"
        pathType: "Prefix"

serverStorage:
    ingress:
        ssl: false
        enabled: false
        hostname: ""
        path: "/"
        pathType: "Prefix"

serverTelemetry:
    ingress:
        ssl: false
        enabled: false
        hostname: ""
        path: "/"
        pathType: "Prefix"

## services
vault:
    server:
        enabled: true
        dev:
            enabled: true
            devRootToken: start123

rabbitmq:
    nameOverride: "rabbitmq"
    auth:
        username: "root"
        password: "start123"

redis:
    nameOverride: "redis"
    auth:
        enabled: true

minio:
    nameOverride: "minio"
    auth:
        rootUser: "admin"
        rootPassword: "start123"

mysql:
    nameOverride: "mysql"
    image:
        pullPolicy: "Always"
    auth:
        rootPassword: "start123"
        replicationPassword: "start123"
    secondary:
        persistence:
            enabled: true
            size: 16Gi
        replicaCount: 2
    primary:
        persistence:
            enabled: true
            size: 16Gi
    architecture: "replication"

grafana:
    nameOverride: "grafana"
    image:
        pullPolicy: "Always"
    admin:
        password: "start123"
    dashboardsProvider:
        enabled: true
    datasources:
        secretName: grafana-datasources
    config:
        useGrafanaIniFile: true
        grafanaIniConfigMap: grafana

grafana-loki:
    nameOverride: "loki"
    image:
        pullPolicy: "Always"
    loki:
        overrideConfiguration:
            limits_config:
                deletion_mode: "filter-and-delete"

prometheus:
    nameOverride: "prometheus"
    alertmanager:
        service:
            type: ClusterIP
    server:
        replicaCount: 2
        service:
            type: ClusterIP
            ports:
                http: 9090
        image:
            pullPolicy: "Always"
        configuration: |
            scrape_configs:
              - job_name: flame-hub-server-core
                static_configs:
                  - targets: ["{{ .Release.Name }}-flame-hub-server-core:3000"]
              - job_name: flame-hub-server-messenger
                static_configs:
                  - targets: ["{{ .Release.Name }}-flame-hub-server-messenger:3000"]
              - job_name: flame-hub-server-storage
                static_configs:
                  - targets: ["{{ .Release.Name }}-flame-hub-server-storage:3000"]
              - job_name: flame-hub-server-telemetry
                static_configs:
                  - targets: ["{{ .Release.Name }}-flame-hub-server-telemetry:3000"]
              - job_name: authup-server-core
                static_configs:
                  - targets: ["{{ .Release.Name }}-authup-server-core:3000"]

harbor:
    enabled: false
    nameOverride: "harbor"
    adminPassword: "start123"
    exposureType: "ingress"
    externalURL: http://localhost
    migration:
        enabled: true
    ingress:
        core:
            hostname: "localhost"
            tls: true
            selfSigned: true
            # secrets:
            #  - name <domain>-tls
            #    certificate: |
            #        ...
            #    key: |
            #       ...
