apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-flame-hub-server-core-worker"
  labels:
    app: "{{ .Release.Name }}-flame-hub-server-core-worker"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-flame-hub-server-core-worker"
  template:
    metadata:
      name: "{{ .Release.Name }}-flame-hub-server-core-worker"
      labels:
        app: "{{ .Release.Name }}-flame-hub-server-core-worker"
        appGroup: "{{ .Release.Name }}-flame-hub"
    spec:
      restartPolicy: Always
      {{- if and (not .Values.externalHarbor.enabled) (include "harbor.host" .)}}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - {{ include "harbor.host" . | quote }}
      {{- end }}
      initContainers:
          -   name: wait-for-rabbitmq
              image: busybox
              command: [
                  'sh',
                  '-c',
                  'until nc -z -v -w30 {{ .Release.Name }}-rabbitmq 5672; do echo "Waiting for rabbitmq..."; sleep 5; done'
              ]
          -   name: wait-for-vault
              image: busybox
              command: [
                  'sh',
                  '-c',
                  'until nc -z -v -w30 {{ .Release.Name }}-vault 8200; do echo "Waiting for vault..."; sleep 5; done'
              ]
          -   name: wait-for-authup
              image: busybox
              command: [
                  'sh',
                  '-c',
                  'until nc -z -v -w30 {{ .Release.Name }}-authup-server-core 3000; do echo "Waiting for authup..."; sleep 5; done'
              ]

          {{- if include "harbor.internalHost" . }}
          -   name: wait-for-harbor
              image: busybox
              command: [
                  'sh',
                  '-c',
                  'until wget --no-check-certificate -qO- https://{{ include "harbor.internalHost" . }}/api/v2.0/ping; do echo "Waiting for harbor..."; sleep 5; done'
              ]
        {{- end }}
      containers:
        - name: "{{ .Release.Name }}-flame-hub-server-core-worker"
          image: {{ include "flameHub.image" . | trim | quote }}
          args: ['core-worker', 'start']
          imagePullPolicy: {{ .Values.image.pullPolicy | trim | quote }}
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "flameHub.effectiveSecretName" .  }}
                  key: redis-connection-string
            - name: VAULT_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "flameHub.effectiveSecretName" .  }}
                  key: vault-connection-string
            - name: RABBITMQ_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "flameHub.effectiveSecretName" .  }}
                  key: rabbitmq-connection-string
            - name: AUTHUP_URL
              value: "http://{{ .Release.Name }}-authup-server-core:3000/"
            - name: CORE_URL
              value: "http://{{ .Release.Name }}-flame-hub-server-core:3000/"
            - name: STORAGE_URL
              value: "http://{{ .Release.Name }}-flame-hub-server-storage:3000/"
          {{- if .Values.serverCoreWorker.useSidecarDinD }}
          volumeMounts:
              -   name: "{{ .Release.Name }}-docker-sidecar-socket"
                  mountPath: /var/run
          {{- else }}
          volumeMounts:
              -   mountPath: "/var/run/docker.sock"
                  name: "{{ .Release.Name }}-flame-hub-server-core-worker-docker-volume"
          securityContext:
              privileged: true
          {{- end }}
          readinessProbe:
              httpGet:
                  path: "/"
                  port: 3000
              initialDelaySeconds: 60
              periodSeconds: 5
              timeoutSeconds: 10
          livenessProbe:
              httpGet:
                  path: "/"
                  port: 3000
              periodSeconds: 10
              timeoutSeconds: 10
        {{ if include "harbor.internalHost" . -}}
        - name: harbor-proxy-sidecar
          image: alpine/socat
          # Proxy HTTPS traffic to the internal harbor. This is a workaround to avoid static hostAliases.
          args: ["TCP-LISTEN:443,fork,bind=127.0.0.1", "TCP:{{ include "harbor.internalHost" . }}:443"]
          securityContext:
            capabilities:
              add: ["NET_BIND_SERVICE"]
        {{- end }}
        {{- if .Values.serverCoreWorker.useSidecarDinD }}
        - name: "{{ .Release.Name }}-docker-sidecar-dind"
          image: "docker:28-dind"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          {{- if not .Values.externalHarbor.enabled }}
          # Microk8s Calico CNI defaults to 1400 MTU, but dind defaults to 1500.
          # This might be different on other k8s providers. If you get mysterious connection errors, check your MTU.
          {{- if include "harbor.host" . }}
          args: ["--insecure-registry", "{{ include "harbor.host" . }}:443", "--mtu", "1350"]
          {{- else }}
          args: ["--mtu", "1350"]
          {{- end }}
          {{- else }}
          args: ["--mtu", "1350"]
          {{- end }}
          volumeMounts:
            - name: "{{ .Release.Name }}-docker-sidecar-graph-storage"
              mountPath: /var/lib/docker
            - name: "{{ .Release.Name }}-docker-sidecar-socket"
              mountPath: /var/run
        {{- end }}
      volumes:
          {{- if .Values.serverCoreWorker.useSidecarDinD }}
          - name: "{{ .Release.Name }}-docker-sidecar-graph-storage"
            emptyDir: {}
          - name: "{{ .Release.Name }}-docker-sidecar-socket"
            emptyDir: {}
          {{- else }}
          -   name: "{{ .Release.Name }}-flame-hub-server-core-worker-docker-volume"
              hostPath:
                  path: "/var/run/docker.sock"
                  type: "Socket"
          {{- end }}
