{{- $hasCerts := include "tls.hasCerts" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-node-ui-deployment
  labels:
    component: flame-ui
    app.kubernetes.io/name: flame-ui
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: flame-node
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      component: flame-ui  
      app.kubernetes.io/name: flame-ui
      app.kubernetes.io/component: ui
      app.kubernetes.io/part-of: flame-node
  replicas: {{ .Values.ui.replicaCount }}
  template:
    metadata:
      annotations:
        {{- with .Values.ui.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        component: flame-ui
        app.kubernetes.io/name: flame-ui
        app.kubernetes.io/component: ui
        app.kubernetes.io/part-of: flame-node
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.ui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: node-ui
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: ui
          env:
            - name: TZ
              value: {{ .Values.timezone | default "Europe/Berlin" }}
            - name: NODE_ENV
              value: {{ .Values.ui.env | default "production" | quote }}
            - name: HTTP_PROXY
              value: {{ .Values.proxy.httpProxy | default "" | quote }}
            - name: HTTPS_PROXY
              value: {{ .Values.proxy.httpsProxy | default "" | quote }}
            - name: NO_PROXY
              value: {{ .Values.proxy.noProxy | default "" | quote }}
            - name: NUXT_PUBLIC_BASE_URL
              value: {{ include "node.hostname" . | default "http://localhost:3000" }}
            - name: NUXT_PUBLIC_HUB_ADAPTER_URL
              value: {{ include "ui.adapter.endpoint" . }}
            - name: NUXT_PUBLIC_ORIGIN
              value: {{ printf "%s/flame/api/auth" (include "node.hostname" .) | default "http://localhost:3000/flame/api/auth" }}
            - name: NUXT_PUBLIC_IDP_PROVIDER
              value: {{ .Values.userIdp.provider | default "keycloak" | quote }}
            - name: NUXT_PUBLIC_IDP_ISSUER
              value: {{ include "ui.userIdp.endpoint" . }}
            - name: NUXT_IDP_CLIENT_ID
              value: {{ .Values.ui.idp.clientId | default "node-ui" | quote }}
            {{- if (eq (include "ui.auth.internal" .) "true") }}
            - name: NUXT_PUBLIC_INTERNAL_KEYCLOAK_URL
              value: {{ include "keycloak.service.endpoint" . }}
            {{- end }}
            - name: NUXT_IDP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ui.keycloak.secretName" . }}
                  key: {{ include "ui.keycloak.secretKey" . }}
            - name: NUXT_AUTH_SECRET
              value: {{ .Values.ui.nuxtAuthSecret | default (randAlphaNum 32) | b64enc }}
            {{- if $hasCerts }}
            - name: NODE_EXTRA_CA_CERTS
              value: "/mnt/certs/certs.pem"
            {{- end }}
            {{- with .Values.ui.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.ui.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          volumeMounts:
            {{- if $hasCerts }}
            - mountPath: "/mnt/certs/certs.pem"
              name: additional-certs
              subPath: "certs.pem"
              readOnly: true
            {{- end }}
            {{- with .Values.ui.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if $hasCerts }}
        - name: additional-certs
          configMap:
            name: {{ include "tls.configMapName" . }}
        {{- end }}
        {{- with .Values.ui.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.ui.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.ui.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.ui.tolerations | nindent 8 }}
