{{- if .Values.ui.idp.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-node-ui-idp-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  nodeUiClientSecret: {{ .Values.ui.idp.clientSecret | b64enc }}
{{- end }}
