{{- if eq .Values.expose.type "ingress" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-node-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "32k"
    {{- with .Values.expose.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    component: flame-ui
    app.kubernetes.io/name: flame-ui
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: flame-node
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- with .Values.expose.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: &host {{ regexReplaceAll "^https?://(.*)" (include "node.hostname" .) "${1}" }}
      http:
        paths:
          - path: /
            pathType: {{ .Values.expose.ingress.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}-node-ui-service
                port:
                  number: 3000
  {{- with .Values.expose.tls.secretName }}
  tls:
    - hosts: [*host]
      secretName: {{ . }}
  {{- end }}
{{- end }}
