{{- if (not .Values.hub.crypto.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ecdh-private-key-secret
  labels:
    app: key
type: Opaque
data:
  private_key.pem: {{ required
  "If no existing secret is provided with a private key, then the contents must be provided in .Values.hub.crypto.privateKey"
  (.Values.hub.crypto.privateKey | default "" | b64enc) }}
{{- end }}
