apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-po-keycloak-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  podOrcClientSecret: {{ include "po.keycloak.clientSecret" . }}

---

{{- if and (not .Values.hub.auth.existingSecret) (not .Values.global.hub.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-po-robot-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  robotSecret: {{ required "A robot secret for the Hub is required." (include "po.hub.robotSecret" .) }}
{{- end }}
