{{- if and .Values.theme.enabled (not .Values.theme.existingConfigMap) .Values.theme.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-authup-theme"
  labels:
    app: "{{ .Release.Name }}-authup-server-core"
data:
{{- range $name, $content := .Values.theme.files }}
  {{ $name }}: |
{{ tpl (toString $content) $ | indent 4 }}
{{- end }}
{{- end }}
