{{- if and .Values.provisioning.enabled (not .Values.provisioning.existingConfigMap) .Values.provisioning.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-authup-provisioning"
  labels:
    app: "{{ .Release.Name }}-authup-server-core"
data:
{{- range $name, $content := .Values.provisioning.files }}
  {{ $name }}: |
{{ tpl (toString $content) $ | indent 4 }}
{{- end }}
{{- end }}
