{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kc-password-secret
data:
  kc-admin-password: YWRtaW4=  # base64 admin
  postgres-password: c3VwZXJzZWNyZXQ= # postgres admin pwd - base64 supersecret
  password: c3VwZXJzZWNyZXQ= # postgres user pwd - base64 supersecret
{{- end }}

---

{{- if not .Values.hub.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hub-robot-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  robotSecret: {{ required "A robot secret for the Hub is required." ( .Values.hub.auth.robotSecret | b64enc ) }}
{{- end }}