apiVersion: v1
kind: ConfigMap
metadata:
  name: flame-default-realm
  namespace: {{ .Release.Namespace }}
data:
  flame.json: |
    {
      "realm" : "flame",
      "defaultSignatureAlgorithm" : "RS256",
      "accessTokenLifespan" : 7200,
      "enabled" : true,
      "requiredCredentials" : [ "password" ],
      "users" : [ {
        "username" : "flameuser",
        "firstName" : "Johnny",
        "lastName" : "Storm",
        "email" : "foo@gmail.com",
        "emailVerified" : true,
        "enabled" : true,
        "totp" : false,
        "credentials" : [ {
          "type" : "password",
          "userLabel" : "My password",
          "secretData" : "{\"value\":\"PYPGjZXTuiL4qZV5yzDJW3B8H91R4qg6/wqgj4FpZ7o=\",\"salt\":\"Dn8bY/M4KsaNYOBB6Wd0Jw==\",\"additionalParameters\":{}}",
          "credentialData" : "{\"hashIterations\":5,\"algorithm\":\"argon2\",\"additionalParameters\":{\"hashLength\":[\"32\"],\"memory\":[\"7168\"],\"type\":[\"id\"],\"version\":[\"1.3\"],\"parallelism\":[\"1\"]}}"
        } ],
        "disableableCredentialTypes" : [ ],
        "requiredActions" : [ ],
        "realmRoles" : [ "default-roles-flame" ],
        "notBefore" : 0,
        "groups" : [ ]
      }, {
        "username" : "service-account-service1",
        "emailVerified" : false,
        "enabled" : true,
        "totp" : false,
        "serviceAccountClientId" : "service1",
        "credentials" : [ ],
        "disableableCredentialTypes" : [ ],
        "requiredActions" : [ ],
        "realmRoles" : [ "default-roles-flame" ],
        "clientRoles" : {
          "realm-management" : [ 
            "create-client", 
            "manage-clients", 
            "view-events", 
            "query-clients" 
          ],
          "service1" : [ "uma_protection" ]
        },
        "notBefore" : 0,
        "groups" : [ ]
      } ],
      "clients" : [ {
        "clientId" : "hub-adapter",
        "name" : "Node Hub Adapter Gateway API",
        "description" : "",
        "rootUrl" : "",
        "adminUrl" : "",
        "baseUrl" : "",
        "surrogateAuthRequired" : false,
        "enabled" : true,
        "alwaysDisplayInConsole" : false,
        "clientAuthenticatorType" : "client-secret",
        "secret" : {{ include "adapter.keycloak.clientSecret" . | b64dec | quote }},
        "redirectUris" : [ "/*" ],
        "webOrigins" : [ "/*" ],
        "notBefore" : 0,
        "bearerOnly" : false,
        "consentRequired" : false,
        "standardFlowEnabled" : true,
        "implicitFlowEnabled" : false,
        "directAccessGrantsEnabled" : true,
        "serviceAccountsEnabled" : true,
        "publicClient" : false
      }, {
        "clientId" : "node-ui",
        "name" : "Node UI",
        "description" : "",
        "rootUrl" : "",
        "adminUrl" : "",
        "baseUrl" : "",
        "surrogateAuthRequired" : false,
        "enabled" : true,
        "alwaysDisplayInConsole" : false,
        "clientAuthenticatorType" : "client-secret",
        "secret" : {{ include "ui.keycloak.clientSecret" . | b64dec | quote }},
        "redirectUris" : {{ include "ui.keycloak.redirectUris" . }},
        "webOrigins" : [ "/*" ],
        "notBefore" : 0,
        "bearerOnly" : false,
        "consentRequired" : false,
        "standardFlowEnabled" : true,
        "implicitFlowEnabled" : false,
        "directAccessGrantsEnabled" : true,
        "serviceAccountsEnabled" : true,
        "publicClient" : false
      }, {
        "clientId" : "service1",
        "name" : "Test service",
        "description" : "",
        "rootUrl" : "",
        "adminUrl" : "",
        "baseUrl" : "",
        "surrogateAuthRequired" : false,
        "enabled" : true,
        "alwaysDisplayInConsole" : false,
        "clientAuthenticatorType" : "client-secret",
        "secret" : {{ include "po.keycloak.clientSecret" . | b64dec | quote }},
        "redirectUris" : [ "/*" ],
        "webOrigins" : [ "/*" ],
        "notBefore" : 0,
        "bearerOnly" : false,
        "consentRequired" : false,
        "standardFlowEnabled" : true,
        "implicitFlowEnabled" : false,
        "directAccessGrantsEnabled" : true,
        "serviceAccountsEnabled" : true,
        "publicClient" : false
      } ]
    }