{{- $ecdhFilePath := "private_key.yaml" }}
{{- if not (.Files.Get $ecdhFilePath) }}
{{- fail (printf "Required file ./%s is missing! Please generate one using the 'Crypto' tab in the Hub for your node" $ecdhFilePath) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ecdh-private-key-secret
  labels:
    app: key
type: Opaque
data:
  private_key.pem: {{ .Files.Get "private_key.pem" | b64enc | quote }}