{{- if .Values.openebs.engines.replicated.mayastor.enabled }}
{{- range .Values.openebs.mayastorConfig.diskPools }}
---
apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  node: {{ .node }}
  disks:
  {{- range .disks }}
    - {{ . | quote }}
  {{- end }}
  {{- if .topology }}
  topology:
    labelled:
      {{- toYaml .topology | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
