apiVersion: v1
kind: Service
metadata:
    name: "{{ .Release.Name }}-rabbitmq"
    labels:
        app: "{{ .Release.Name }}-rabbitmq"
spec:
    clusterIP: None
    selector:
        app: "{{ .Release.Name }}-rabbitmq"
    ports:
        -   name: amqp
            protocol: TCP
            port: 5672
            targetPort: amqp
