apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hub-adapter-deployment
spec:
  selector:
    matchLabels:
      component: hub-adapter-service
      version: {{ .Chart.AppVersion }}
      deployment-id:  {{ .Release.Name }}
  replicas: {{ .Values.hubAdapter.replicaCount }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/hub-adapter/secret.yaml") . | sha256sum }}
        {{- with .Values.hubAdapter.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        component: hub-adapter-service
        version: {{ .Chart.AppVersion }}
        deployment-id:  {{ .Release.Name }}
        {{- with .Values.hubAdapter.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.hubAdapter.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.hubAdapter.podSecurityContext | nindent 8 }}
      containers:
        - name: api-gateway
          securityContext:
            {{- toYaml .Values.hubAdapter.securityContext | nindent 12 }}
          image: "{{ .Values.hubAdapter.image.repository }}:{{ .Values.hubAdapter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.hubAdapter.image.pullPolicy }}
          ports:
            - containerPort: 5000
              name: healthcp
          env:
            - name: API_ROOT_PATH
              value: {{ (include "adapter.root.path" .) | default "" }}
            - name: API_CLIENT_ID
              value: {{ .Values.hubAdapter.idp.clientId | default "hub-adapter" | quote }}
            - name: API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "adapter.keycloak.secretName" . }}
                  key: {{ include "adapter.keycloak.secretKey" . }}
            - name: IDP_URL
              value: {{ include "adapter.userIdp.endpoint" . }}
            - name: NODE_SVC_OIDC_URL
              value: {{ printf "http://%s-keycloak:80%s/realms/flame" .Release.Name .Values.hubAdapter.idp.httpRelativePath }}
            - name: OVERRIDE_JWKS
              value: {{ include "adapter.jwks.endpoint" . }}
            - name: RESULTS_SERVICE_URL
              value: {{ printf "http://%s-node-result-service:8080" .Release.Name }}
            - name: PODORC_SERVICE_URL
              value: {{ printf "http://%s-po-service:8000" .Release.Name }}
            - name: KONG_ADMIN_SERVICE_URL
              value: {{ printf "http://%s-kong-admin:80" .Release.Name }}
            - name: HUB_SERVICE_URL
              value: {{ .Values.hub.endpoints.core | default "https://core.privateaim.dev" | quote }}
            - name: HUB_AUTH_SERVICE_URL
              value: {{ .Values.hub.endpoints.auth | default "https://auth.privateaim.dev" | quote }}
            - name: HUB_ROBOT_USER
              value: {{ required "A robot ID for the Hub is required." .Values.hub.auth.robotUser | quote }}  # To be properly filled in
            - name: HUB_ROBOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "hub.secretName" . }}
                  key: robotSecret
            {{- with .Values.hubAdapter.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.hubAdapter.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.hubAdapter.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.hubAdapter.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.hubAdapter.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.hubAdapter.volumes | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.hubAdapter.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.hubAdapter.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.hubAdapter.tolerations | nindent 8 }}
