apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hub-adapter-service
  labels:
    component: flame-hub-adapter
    app.kubernetes.io/name: flame-hub-adapter
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: flame-node
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
  - name: api
    port: 5000
  selector:
    component: flame-hub-adapter
    app.kubernetes.io/name: flame-hub-adapter
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: flame-node
    app.kubernetes.io/instance: {{ .Release.Name }}
