apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-flame-hub-client-ui"
  labels:
    app: "{{ .Release.Name }}-flame-hub-client-ui"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-flame-hub-client-ui"
      version: {{ .Chart.AppVersion }}
      deployment-id: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: "{{ .Release.Name }}-flame-hub-client-ui"
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: "{{ .Release.Name }}-flame-hub-client-ui"
        version: {{ .Chart.AppVersion }}
        deployment-id: {{ .Release.Name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      containers:
        - name: "{{ .Release.Name }}-flame-hub-client-ui"
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          args: ["ui", "start"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            {{- with .Values.cookieDomain }}
              -   name: NUXT_PUBLIC_COOKIE_DOMAIN
                  value: "{{- toString . | trim }}"
            {{- end }}
              -   name: NUXT_STORAGE_URL
                  value: "http://{{ .Release.Name }}-flame-hub-server-storage:3000/"
              -   name: NUXT_PUBLIC_STORAGE_URL
                  value: {{ include "storage.publicURL" . | trim | quote }}
              -   name: NUXT_CORE_URL
                  value: "http://{{ .Release.Name }}-flame-hub-server-core:3000/"
              -   name: NUXT_PUBLIC_CORE_URL
                  value: {{ include "core.publicURL" . | trim | quote }}
              -   name: NUXT_AUTHUP_URL
                  value: "http://{{ .Release.Name }}-authup-server-core:3000/"
              -   name: NUXT_PUBLIC_AUTHUP_URL
                  value: {{ include "authup.publicURL" . |  trim | quote }}
              {{- with .Values.env }}
              {{- toYaml . | nindent 12 }}
              {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}

