{{- if and .Values.openebs.engines.replicated.mayastor.enabled .Values.openebs.mayastorConfig.storageClasses }}
{{- range .Values.openebs.mayastorConfig.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
provisioner: io.openebs.csi-mayastor
parameters:
  protocol: {{ .protocol | default "nvmf" }}
  repl: "{{ .replicationFactor }}"
{{- end }}
{{- end }}
