{{- if .Values.harbor.enabled }}
# Additional Alias service for Redis that Harbor can reference with a fixed name (without templating)
apiVersion: v1
kind: Service
metadata:
  name: redis-internal
spec:
  type: ExternalName
  # needs fully qualified name with namespace
  externalName: {{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}

