apiVersion: v1
kind: Service
metadata:
    name: {{ include "flameHub.redis.host" . | quote }}
    labels:
        app: "{{ .Release.Name }}-redis"
spec:
    clusterIP: None
    selector:
        app: "{{ .Release.Name }}-redis"
    ports:
        -   name: redis
            protocol: TCP
            port: {{ include "flameHub.redis.port" . }}
            targetPort: redis
