## Global variables
global:
  hub:
    endpoints:
      ## @param global.hub.endpoints.auth Hub Auth API endpoint. Overrides broker.HUB_AUTH_BASE_URL if provided
      auth: https://auth.privateaim.dev
      ## @param global.hub.endpoints.core Hub Core API endpoint. Overrides broker.HUB_BASE_URL if provided
      core: https://core.privateaim.dev
      ## @param global.hub.endpoints.core Hub Core API endpoint. Overrides broker.HUB_BASE_URL if provided
      messenger: https://messenger.privateaim.dev
    auth:
      ## @param global.hub.auth.robotUser Robot user ID. Overrides broker.HUB_AUTH_ROBOT_ID if provided
      robotUser: ""
      ## @param global.hub.auth.robotSecret Robot secret. Overrides broker.HUB_AUTH_ROBOT_SECRET if provided
      robotSecret: ""
      ## @param global.hub.auth.existingSecret Valid robot secret encoded in a k8s secret. Overrides hub.auth.existingSecret if provided
      existingSecret: ""

common:
  timezone: Europe/Berlin
broker:
  AUTH_JWKS_URL: ""
  HUB_BASE_URL: https://api.privateaim.dev/
  HUB_AUTH_BASE_URL: https://auth.privateaim.dev/
  HUB_MESSENGER_BASE_URL: "https://messenger.privateaim.dev/"
  HUB_AUTH_ROBOT_ID: ""
  HUB_AUTH_ROBOT_SECRET: ""

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/privateaim/node-message-broker
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  # This sets the pull policy for images.
  pullPolicy: Always

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  privileged: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8090
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 10
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8090
  initialDelaySeconds: 60
  periodSeconds: 5
  timeoutSeconds: 10

# Additional environment variables on the output Deployment definition.
env: []
# - name: FOO
#   value: bar

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}
tolerations: []
affinity: {}

hub:
  endpoints:
    ## @param global.hub.endpoints.auth Hub Auth API endpoint. Overrides broker.HUB_AUTH_BASE_URL if provided
    auth: https://auth.privateaim.dev
    ## @param global.hub.endpoints.core Hub Core API endpoint. Overrides broker.HUB_BASE_URL if provided
    core: https://core.privateaim.dev
    ## @param global.hub.endpoints.core Hub Core API endpoint. Overrides broker.HUB_BASE_URL if provided
    messenger: https://messenger.privateaim.dev
  auth:
    ## @param global.hub.auth.robotUser Robot user ID. Overrides broker.HUB_AUTH_ROBOT_ID if provided
    robotUser: ""
    ## @param global.hub.auth.robotSecret Robot secret. Overrides broker.HUB_AUTH_ROBOT_SECRET if provided
    robotSecret: ""
    ## @param global.hub.auth.existingSecret Valid robot secret encoded in a k8s secret. Overrides hub.auth.existingSecret if provided
    existingSecret:
  crypto:
    ## @param hub.crypto.privateKey Content of the private key to be added to the secret. Need to use the "|" scalar:
    ## https://yaml.org/spec/1.2.2/#812-literal-style; https://helm.sh/docs/chart_template_guide/yaml_techniques/
    ##
    privateKey: ""
    ## @param hub.crypto.existingSecret Existing secret containing the private key for the node
    ## Create this secret following the steps below:
    ## 1) Generate your public and private key pair using the "Crypto" tab in the Hub
    ## 2) Save the private key as 'private_key.pem' (it must use this name)
    ## 3) Run the command below where SECRET_NAME is the name of the secret you want to create:
    ##       kubectl create secret generic SECRET_NAME --from-file=./private_key.pem
    existingSecret: ""


node-message-broker-db:
  global:
    defaultStorageClass: ""
  architecture: "standalone"
  useStatefulSet: true
  replicaCount: 1

  auth:
    enabled: false

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi

  persistence:
    size: 100Mi
    storageClass: ""

  serviceAccount:
    create: false

  networkPolicy:
    enabled: false
