apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-flame-hub-server-storage
    labels:
        app: {{ .Release.Name }}-flame-hub-server-storage
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Release.Name }}-flame-hub-server-storage
    template:
        metadata:
            name: {{ .Release.Name }}-flame-hub-server-storage
            labels:
                app: {{ .Release.Name }}-flame-hub-server-storage
                appGroup: "{{ .Release.Name }}-flame-hub"
        spec:
            restartPolicy: Always
            initContainers:
                -   name: wait-for-db
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-postgresql-primary 5432; do echo "Waiting for db..."; sleep 5; done'
                    ]
                -   name: wait-for-redis
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-redis-master 6379; do echo "Waiting for redis..."; sleep 5; done'
                    ]
                -   name: wait-for-rabbitmq
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-rabbitmq 5672; do echo "Waiting for rabbitmq..."; sleep 5; done'
                    ]
                -   name: wait-for-minio
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-minio 9000; do echo "Waiting for rabbitmq..."; sleep 5; done'
                    ]
                -   name: wait-for-vault
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-vault 8200; do echo "Waiting for vault..."; sleep 5; done'
                    ]
                -   name: wait-for-authup
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-authup-server-core 3000; do echo "Waiting for authup..."; sleep 5; done'
                    ]
            containers:
                -   name: "{{ .Release.Name }}-flame-hub-server-storage"
                    image: {{ include "flameHub.image" . | trim | quote }}
                    args: ["storage", "cli", "start"]
                    imagePullPolicy: {{ .Values.image.pullPolicy | trim | quote }}
                    ports:
                        -   containerPort: 3000
                            protocol: TCP
                    env:
                        -   name: REDIS_CONNECTION_STRING
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "flameHub.effectiveSecretName" .  }}
                                    key: redis-connection-string
                        -   name: RABBITMQ_CONNECTION_STRING
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "flameHub.effectiveSecretName" .  }}
                                    key: rabbitmq-connection-string
                        -   name: VAULT_CONNECTION_STRING
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "flameHub.effectiveSecretName" .  }}
                                    key: vault-connection-string
                        -   name: MINIO_CONNECTION_STRING
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "flameHub.effectiveSecretName" .  }}
                                    key: minio-connection-string
                        -   name: AUTHUP_URL
                            value: "http://{{ .Release.Name }}-authup-server-core:3000/"
                        -   name: DB_TYPE
                            value: "postgres"
                        -   name: DB_HOST
                            value: "{{ .Release.Name }}-postgresql-primary"
                        -   name: DB_USERNAME
                            value: "postgres"
                        -   name: DB_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "flameHub.effectiveSecretName" .  }}
                                    key: postgresql-password
                        -   name: DB_DATABASE
                            value: "storage"
                    resources:
                        requests:
                            memory: "512Mi"
                        limits:
                            memory: "2048Mi"
                    readinessProbe:
                        httpGet:
                            path: "/"
                            port: 3000
                        initialDelaySeconds: 60
                        periodSeconds: 5
                        timeoutSeconds: 10
                    livenessProbe:
                        httpGet:
                            path: "/"
                            port: 3000
                        failureThreshold: 3
                        periodSeconds: 60
                        initialDelaySeconds: 90
