{{- if and (eq .Values.expose.type "gateway") .Values.victorialogs.enabled .Values.victorialogs.ingress.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-victorialogs-route
  labels:
    component: victoria-logs
    app.kubernetes.io/name: victoria-logs
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: flame-node
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  parentRefs:
  {{- include "flame-node.gateway.parentRefs" . | nindent 2 }}
  hostnames:
  - {{ include "flame-node.gateway.routeHostname" . | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /logs
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: {{ .Release.Name }}-victorialogs-server
      port: 9428
{{- end }}
