{{- if and (not .Values.hub.auth.existingSecret) (not .Values.global.hub.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-node-message-broker-hub-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  robot_secret: {{ required "A robot secret for the Hub is required." (include "broker.hub.robotSecret" .) }}
{{- end }}
