{{/*
Expand the name of the chart.
*/}}
{{- define "flame-hub.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "flame-hub.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "flame-hub.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "flame-hub.labels" -}}
helm.sh/chart: {{ include "flame-hub.chart" . }}
{{ include "flame-hub.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "flame-hub.selectorLabels" -}}
app.kubernetes.io/name: {{ include "flame-hub.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "flame-hub.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "flame-hub.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}


{{- define "flameHub.image" -}}
{{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
{{- end -}}

{{- define "flameHub.effectiveSecretName" -}}
{{- if .Values.auth.existingSecret -}}
{{ .Values.auth.existingSecret }}
{{- else -}}
{{ .Values.auth.secretName }}
{{- end -}}
{{- end -}}


{{- define "flameHub.postgresql.host" -}}
{{- required "global.flameHub.postgresql.host is required" .Values.global.flameHub.postgresql.host -}}
{{- end -}}

{{- define "flameHub.postgresql.secretName" -}}
{{- $pg := .Values.global.flameHub.postgresql -}}
{{- $pg.existingSecret | default (required "global.flameHub.postgresql.secretName is required" $pg.secretName) -}}
{{- end -}}


{{/*
Name/host of the chart-managed Redis Service. Read from global.flameHub.redis so the value also resolves inside
subcharts (Helm shares only `global`); the authup subchart reaches it through this helper.
*/}}
{{- define "flameHub.redis.host" -}}
{{- $redis := (((.Values.global).flameHub).redis) | default dict -}}
{{- $redis.host | default (printf "%s-redis" .Release.Name) -}}
{{- end -}}

{{- define "flameHub.redis.port" -}}
{{- $redis := (((.Values.global).flameHub).redis) | default dict -}}
{{- $redis.port | default 6379 -}}
{{- end -}}


{{- define "flameHub.harbor.secretName" -}}
{{- .Values.harbor.existingSecret | default (required "harbor.secretName is required" .Values.harbor.secretName) -}}
{{- end -}}

{{/*
Full name of the seaweedfs subchart release, mirroring its "seaweedfs.fullname" helper
so resource names can be derived from the parent chart context.
*/}}
{{- define "flameHub.seaweedfs.fullname" -}}
{{- if .Values.seaweedfs.fullnameOverride -}}
{{- .Values.seaweedfs.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default "seaweedfs" .Values.seaweedfs.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Whether the local-dev in-cluster Harbor proxy (hostAliases + socat sidecar + dind
insecure-registry) should be rendered. Truthy only when harborProxy.enabled is set, Harbor
is in-cluster (not externalHarbor), and an internal Harbor host resolves.
*/}}
{{- define "flameHub.harborProxy.enabled" -}}
{{- if and .Values.harborProxy.enabled (not .Values.externalHarbor.enabled) -}}
{{- include "harbor.internalHost" . -}}
{{- end -}}
{{- end -}}

{{/*
Host of the SeaweedFS S3 gateway (served by the all-in-one pod on port 8333).
*/}}
{{- define "flameHub.seaweedfs.s3Host" -}}
{{- printf "%s-all-in-one" (include "flameHub.seaweedfs.fullname" .) -}}
{{- end -}}

{{/*
Name of the Secret holding the SeaweedFS S3 credentials: a user-supplied Secret when
seaweedfs.s3.existingConfigSecret is set, otherwise the one generated by the subchart.
*/}}
{{- define "flameHub.seaweedfs.s3SecretName" -}}
{{- .Values.seaweedfs.s3.existingConfigSecret | default (printf "%s-s3-secret" (include "flameHub.seaweedfs.fullname" .)) -}}
{{- end -}}

{{/*
Validate ingress mode: global path-based ingress and individual service ingresses are mutually exclusive.
*/}}
{{- define "flameHub.validateIngressMode" -}}
{{- $globalIngressEnabled := .Values.global.flameHub.ingress.enabled -}}
{{- $individualIngressEnabled := or
    .Values.clientUI.ingress.enabled
    .Values.serverCore.ingress.enabled
    .Values.serverMessenger.ingress.enabled
    .Values.serverStorage.ingress.enabled
    .Values.serverTelemetry.ingress.enabled
    .Values.authup.server.ingress.enabled
-}}
{{- if and $globalIngressEnabled $individualIngressEnabled -}}
{{- fail "Ingress configuration is mutually exclusive: disable global.flameHub.ingress.enabled or disable individual service ingress settings (clientUI, serverCore, serverMessenger, serverStorage, serverTelemetry, authup)." -}}
{{- end -}}
{{- end -}}

{{/*
Validate that the goharbor subchart's un-templatable literals still point at the effective
flame-hub PostgreSQL and Harbor names.
*/}}
{{- define "flameHub.validateNames" -}}
{{- if and .Values.harbor.enabled (not .Values.externalHarbor.enabled) -}}
{{- $pgHost := include "flameHub.postgresql.host" . -}}
{{- $pgSecret := include "flameHub.postgresql.secretName" . -}}
{{- $harborSecret := include "flameHub.harbor.secretName" . -}}
{{- $ext := .Values.harbor.database.external -}}
{{- if eq (.Values.harbor.database.type | default "external") "external" -}}
{{- if ne ($ext.host | toString) $pgHost -}}
{{- fail (printf "harbor.database.external.host (%q) must equal the effective PostgreSQL host global.flameHub.postgresql.host (%q)." ($ext.host | toString) $pgHost) -}}
{{- end -}}
{{- if ne ($ext.existingSecret | toString) $pgSecret -}}
{{- fail (printf "harbor.database.external.existingSecret (%q) must equal the effective PostgreSQL secret (%q = global.flameHub.postgresql existingSecret|secretName)." ($ext.existingSecret | toString) $pgSecret) -}}
{{- end -}}
{{- if ne ($ext.username | toString) (.Values.postgresql.auth.username | toString) -}}
{{- fail (printf "harbor.database.external.username (%q) must equal postgresql.auth.username (%q)." ($ext.username | toString) (.Values.postgresql.auth.username | toString)) -}}
{{- end -}}
{{- end -}}
{{- if ne (.Values.harbor.existingSecretAdminPassword | toString) $harborSecret -}}
{{- fail (printf "harbor.existingSecretAdminPassword (%q) must equal the effective Harbor secret (%q = harbor existingSecret|secretName)." (.Values.harbor.existingSecretAdminPassword | toString) $harborSecret) -}}
{{- end -}}
{{- if ne (.Values.harbor.existingSecretSecretKey | toString) $harborSecret -}}
{{- fail (printf "harbor.existingSecretSecretKey (%q) must equal the effective Harbor secret (%q = harbor existingSecret|secretName)." (.Values.harbor.existingSecretSecretKey | toString) $harborSecret) -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Generate a pair of HTTP (+ optional HTTPS) gateway listeners for a given name and hostname.
Expects a dict with keys: name, hostname, tls (the global TLS config dict).
*/}}
{{- define "flameHub.gatewayListeners" -}}
- name: {{ .name }}-http
  hostname: {{ .hostname | quote }}
  protocol: HTTP
  port: 80
  allowedRoutes:
    namespaces:
      from: Same
{{- if .tls.enabled }}
- name: {{ .name }}-https
  hostname: {{ .hostname | quote }}
  protocol: HTTPS
  port: 443
  tls:
    mode: {{ .tls.mode | default "Terminate" }}
    certificateRefs:
      - name: {{ .tls.certificateRef }}
        {{- if .tls.certificateRefNamespace }}
        namespace: {{ .tls.certificateRefNamespace }}
        {{- end }}
  allowedRoutes:
    namespaces:
      from: Same
{{- end }}
{{- end -}}

{{/*
Return the parentRefs list item for HTTPRoutes targeting the Hub Gateway.
When global.flameHub.gatewayApi.gateway.external is true, references the user-supplied external Gateway;
otherwise references the chart-managed Gateway.
*/}}
{{- define "flame-hub.gateway.parentRefs" -}}
{{- $gw := .Values.global.flameHub.gatewayApi.gateway -}}
{{- $pr := $gw.parentRef | default dict -}}
{{- if default false $gw.external -}}
{{- $name := required "global.flameHub.gatewayApi.gateway.parentRef.name is required when global.flameHub.gatewayApi.gateway.external=true" $pr.name -}}
- group: gateway.networking.k8s.io
  kind: Gateway
  name: {{ $name }}
  {{- if $pr.namespace }}
  namespace: {{ $pr.namespace }}
  {{- end }}
  {{- if $pr.sectionName }}
  sectionName: {{ $pr.sectionName }}
  {{- end }}
{{- else -}}
- name: {{ .Release.Name }}-flame-hub-gateway
{{- end -}}
{{- end -}}
