{{- if .Values.global.flameHub.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Release.Name }}-flame-hub
    annotations:
        {{- range $key, $value := .Values.global.flameHub.ingress.annotations }}
        {{ $key }}: {{ tpl ($value | toString) $ | quote }}
        {{- end }}
spec:
    {{- if .Values.global.flameHub.ingress.className }}
    ingressClassName: {{ .Values.global.flameHub.ingress.className }}
    {{- end }}
    rules:
        - host: {{ .Values.global.flameHub.ingress.hostname }}
          http:
              paths:
                  - path: /grafana(/|$)(.*)
                    pathType: "ImplementationSpecific"
                    backend:
                        service:
                            name: {{ .Release.Name }}-grafana
                            port:
                                number: 3000
                  - path: /core(/|$)(.*)
                    pathType: "ImplementationSpecific"
                    backend:
                        service:
                            name: {{ .Release.Name }}-flame-hub-server-core
                            port:
                                number: 3000
                  - path: /messenger(/|$)(.*)
                    pathType: "ImplementationSpecific"
                    backend:
                        service:
                            name: {{ .Release.Name }}-flame-hub-server-messenger
                            port:
                                number: 3000
                  - path: /storage(/|$)(.*)
                    pathType: "ImplementationSpecific"
                    backend:
                        service:
                            name: {{ .Release.Name }}-flame-hub-server-storage
                            port:
                                number: 3000
                  - path: /telemetry(/|$)(.*)
                    pathType: "ImplementationSpecific"
                    backend:
                        service:
                            name: {{ .Release.Name }}-flame-hub-server-telemetry
                            port:
                                number: 3000
                  - path: /auth(/|$)(.*)
                    pathType: "ImplementationSpecific"
                    backend:
                        service:
                            name: {{ .Release.Name }}-authup-server-core
                            port:
                                number: 3000
                  - path: /()(.*)
                    pathType: "ImplementationSpecific"
                    backend:
                        service:
                            name: {{ .Release.Name }}-flame-hub-client-ui
                            port:
                                number: 3000
{{- end }}

{{/* Harbor ingress is independent of the above ingress since Harbor always needs its own hostname */}}
{{- if and .Values.harbor.enabled (not .Values.externalHarbor.enabled) .Values.harbor.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Release.Name }}-harbor
    annotations:
        {{- range $key, $value := .Values.harbor.ingress.annotations }}
        {{ $key }}: {{ tpl ($value | toString) $ | quote }}
        {{- end }}
spec:
    {{- if .Values.harbor.ingress.className }}
    ingressClassName: {{ .Values.harbor.ingress.className }}
    {{- end }}
    rules:
        - host: {{ include "harbor.host" . }}
          http:
              paths:
                  - path: /
                    pathType: "ImplementationSpecific"
                    backend:
                        service: 
                            name: {{ .Release.Name }}-harbor
                            port:
                                number: 443
{{- end }}