{{- $clusterName := include "flameHub.postgresql.clusterName" . -}}
{{- $appUsername := .Values.postgresql.auth.appUsername -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $clusterName }}
  labels:
    {{- include "flame-hub.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgresql.cluster.instances }}
  imageName: {{ .Values.postgresql.cluster.imageName | quote }}
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  storage:
    size: {{ .Values.postgresql.cluster.storage.size | quote }}
    {{- with .Values.postgresql.cluster.storage.storageClass }}
    storageClass: {{ . | quote }}
    {{- end }}
  postgresql:
    parameters:
      {{- toYaml .Values.postgresql.cluster.postgresql.parameters | nindent 6 }}
  managed:
    roles:
      - name: {{ $appUsername }}
        ensure: present
        login: true
        superuser: false
        inherit: true
        passwordSecret:
          name: {{ .Values.postgresql.auth.appAuthSecretName | quote }}
  bootstrap:
    initdb:
      database: postgres
      owner: postgres

