{{- $clusterName := include "flameHub.postgresql.clusterName" . -}}
{{- $owner := .Values.postgresql.auth.appUsername -}}
{{- range .Values.postgresql.databases }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ $clusterName }}-{{ . | replace "_" "-" }}
  labels:
    {{- include "flame-hub.labels" $ | nindent 4 }}
spec:
  name: {{ . | quote }}
  owner: {{ $owner }}
  cluster:
    name: {{ $clusterName }}
{{- end }}

