# Routing — choose 'ingress', 'gateway', or 'none'
expose:
  type: ingress
  hostname: "my.domain.de"
  ingress:
    className: "nginx"

## Hub services and data
hub:
  ## Credentials used for retrieving a valid token from the hub using a robot account
  auth:
    clientID:
    clientSecret:
  ## Values required by the storage service for encrypting intermediate results sent to the Hub
  crypto:
    ## @param hub.crypto.privateKey Content of the private key to be added to the secret. Need to use the "|" scalar:
    ## https://yaml.org/spec/1.2.2/#812-literal-style
    ##
    privateKey:
    ## @param hub.crypto.existingSecret Existing secret containing the private key for the node
    ## Create this secret following the steps below:
    ## 1) Generate your public and private key pair using the "Crypto" tab in the Hub
    ## 2) Save the private key as 'private_key.pem' (it must use this name)
    ## 3) Run the command below where SECRET_NAME is the name of the secret you want to create:
    ##       kubectl create secret generic SECRET_NAME --from-file=./private_key.pem
    existingSecret:

# keycloak values
keycloak:
  auth:
    adminUser: admin
    adminPassword: admin

proxy:
  httpProxy:
  httpsProxy:
  noProxy:

## If enabled, this will deploy a FHIR and MinIO server that can be used for testing
flame-node-data-store:
  enabled: false

## @param rbac Role Based Access Control settings for authenticated users. Controls feature access in the node UI
rbac:
  ## @param rbac.roleClaimName A period "." separated list of keys leading to the claim in the OIDC token that contains the user's roles
  ## If left blank, RBAC will be disabled and all authenticated users will have full access.
  ## The default value is for the bundled Keycloak instance
  roleClaimName: "resource_access.node-ui.roles"
  ## @param rbac.adminRole Role name for users who have full access and control as defined in the IDP
  adminRole: "admin"
  ## @param rbac.stewardRole Role name for users who can only modify data stores as defined in the IDP
  stewardRole: "steward"
  ## @param rbac.researcherRole Role name for users who can only modify analyses as defined in the IDP
  researcherRole: "researcher"