# Global values
global:
  hub:
    endpoints:
      auth: https://auth.privateaim.dev
      core: https://core.privateaim.dev
      messenger: https://messenger.privateaim.dev
      storage: https://storage.privateaim.dev
    auth:
      robotUser:
      robotSecret:
  node:
    ingress:
      enabled: true
      hostname: "https://my.domain.de"
  keycloak:
    ## @param global.keycloak.hostname Hostname for a separate instance of keycloak. Overrides the /keycloak subpath
    ## Leave this blank unless you want to use your own IDP
    hostname:

# keycloak values
keycloak:
  auth:
    adminUser: admin
    adminPassword: admin

flame-node-result-service:
  hub:
    crypto:
      ## @param hub.crypto.privateKey Content of the private key to be added to the secret. Need to use the "|" scalar:
      ## https://yaml.org/spec/1.2.2/#812-literal-style; https://helm.sh/docs/chart_template_guide/yaml_techniques/
      ##
      privateKey:
      ## @param hub.crypto.existingSecret Existing secret containing the private key for the node
      ## Create this secret following the steps below:
      ## 1) Generate your public and private key pair using the "Crypto" tab in the Hub
      ## 2) Save the private key as 'private_key.pem' (it must use this name)
      ## 3) Run the command below where SECRET_NAME is the name of the secret you want to create:
      ##       kubectl create secret generic SECRET_NAME --from-file=./private_key.pem
      existingSecret:

flame-node-message-broker:
  # TODO: This is a duplication of the same block from the result service.
  #       However, this can only be resolved once the project structure is inverted allowing for proper usage of
  #       global values that can be re-used throughout different sub-charts.
  hub:
    crypto:
      ## @param hub.crypto.privateKey Content of the private key to be added to the secret. Need to use the "|" scalar:
      ## https://yaml.org/spec/1.2.2/#812-literal-style; https://helm.sh/docs/chart_template_guide/yaml_techniques/
      ##
      privateKey:
      ## @param hub.crypto.existingSecret Existing secret containing the private key for the node
      ## Create this secret following the steps below:
      ## 1) Generate your public and private key pair using the "Crypto" tab in the Hub
      ## 2) Save the private key as 'private_key.pem' (it must use this name)
      ## 3) Run the command below where SECRET_NAME is the name of the secret you want to create:
      ##       kubectl create secret generic SECRET_NAME --from-file=./private_key.pem
      existingSecret:
