apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-flame-hub-server-telemetry
    labels:
        app: {{ .Release.Name }}-flame-hub-server-telemetry
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Release.Name }}-flame-hub-server-telemetry
    template:
        metadata:
            name: {{ .Release.Name }}-flame-hub-server-telemetry
            labels:
                app: {{ .Release.Name }}-flame-hub-server-telemetry
                appGroup: "{{ .Release.Name }}-flame-hub"
        spec:
            restartPolicy: Always
            initContainers:
                -   name: wait-for-db
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-mysql-primary 3306; do echo "Waiting for db..."; sleep 5; done'
                    ]
                -   name: wait-for-redis
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-redis-master 6379; do echo "Waiting for redis..."; sleep 5; done'
                    ]
                -   name: wait-for-rabbitmq
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-rabbitmq 5672; do echo "Waiting for rabbitmq..."; sleep 5; done'
                    ]
                -   name: wait-for-vault
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-vault 8200; do echo "Waiting for vault..."; sleep 5; done'
                    ]
                -   name: wait-for-authup
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-authup-server-core 3000; do echo "Waiting for authup..."; sleep 5; done'
                    ]
                - name: wait-for-loki
                  image: busybox
                  command: [
                    'sh',
                    '-c',
                    'until nc -z -v -w30 {{ .Release.Name }}-loki-query-frontend 3100; do echo "Waiting for loki..."; sleep 5; done'
                  ]
            containers:
                -   name: "{{ .Release.Name }}-flame-hub-server-telemetry"
                    image: {{ include "flameHub.image" . | trim | quote }}
                    args: ["telemetry", "cli", "start"]
                    imagePullPolicy: {{ .Values.image.pullPolicy | trim | quote }}
                    ports:
                        -   containerPort: 3000
                            protocol: TCP
                    env:
                        -   name: REDIS_CONNECTION_STRING
                            value: "redis://default:{{ .Values.global.redis.password }}@{{ .Release.Name }}-redis-master"
                        -   name: RABBITMQ_CONNECTION_STRING
                            value: "amqp://root:start123@{{ .Release.Name }}-rabbitmq"
                        -   name: VAULT_CONNECTION_STRING
                            value: "start123@http://{{ .Release.Name }}-vault:8200/v1/"
                        -   name: AUTHUP_URL
                            value: "http://{{ .Release.Name }}-authup-server-core:3000/"
                        -   name: LOKI_COMPACTOR_URL
                            value: "http://{{ .Release.Name }}-loki-compactor:3100/"
                        -   name: LOKI_DISTRIBUTOR_URL
                            value: "http://{{ .Release.Name }}-loki-distributor:3100/"
                        -   name: LOKI_QUERIER_URL
                            value: "http://{{ .Release.Name }}-loki-query-frontend:3100/"
                        -   name: DB_TYPE
                            value: "mysql"
                        -   name: DB_HOST
                            value: "{{ .Release.Name }}-mysql-primary"
                        -   name: DB_USERNAME
                            value: "root"
                        -   name: DB_PASSWORD
                            value: "start123"
                        -   name: DB_DATABASE
                            value: "telemetry"
                    resources:
                        requests:
                            memory: "512Mi"
                        limits:
                            memory: "2048Mi"
                    readinessProbe:
                        httpGet:
                            path: "/"
                            port: 3000
                        initialDelaySeconds: 60
                        periodSeconds: 5
                        timeoutSeconds: 10
                    livenessProbe:
                        httpGet:
                            path: "/"
                            port: 3000
                        failureThreshold: 3
                        periodSeconds: 60
                        initialDelaySeconds: 90
