apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-flame-hub-server-telemetry
    labels:
        app: {{ .Release.Name }}-flame-hub-server-telemetry
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Release.Name }}-flame-hub-server-telemetry
    template:
        metadata:
            name: {{ .Release.Name }}-flame-hub-server-telemetry
            labels:
                app: {{ .Release.Name }}-flame-hub-server-telemetry
                appGroup: "{{ .Release.Name }}-flame-hub"
        spec:
            restartPolicy: Always
            initContainers:
                -   name: wait-for-db
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ include "flameHub.postgresql.host" . }} 5432; do echo "Waiting for db..."; sleep 5; done'
                    ]
                -   name: wait-for-redis
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-redis-master 6379; do echo "Waiting for redis..."; sleep 5; done'
                    ]
                -   name: wait-for-rabbitmq
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-rabbitmq 5672; do echo "Waiting for rabbitmq..."; sleep 5; done'
                    ]
                -   name: wait-for-authup
                    image: busybox
                    command: [
                        'sh',
                        '-c',
                        'until nc -z -v -w30 {{ .Release.Name }}-authup-server-core 3000; do echo "Waiting for authup..."; sleep 5; done'
                    ]
                - name: wait-for-vl
                  image: busybox
                  command: [
                    'sh',
                    '-c',
                    'until nc -z -v -w30 {{ .Release.Name }}-victoria-logs-vlinsert 9481; do echo "Waiting for victoria-logs..."; sleep 5; done'
                  ]
            containers:
                -   name: "{{ .Release.Name }}-flame-hub-server-telemetry"
                    image: {{ include "flameHub.image" . | trim | quote }}
                    args: ["telemetry", "cli", "start"]
                    imagePullPolicy: {{ .Values.image.pullPolicy | trim | quote }}
                    ports:
                        -   containerPort: 3000
                            protocol: TCP
                    env:
                        -   name: REDIS_CONNECTION_STRING
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "flameHub.effectiveSecretName" .  }}
                                    key: redis-connection-string
                        -   name: RABBITMQ_CONNECTION_STRING
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "flameHub.effectiveSecretName" .  }}
                                    key: rabbitmq-connection-string
                        -   name: AUTHUP_URL
                            value: "http://{{ .Release.Name }}-authup-server-core:3000/"
                        -   name: VICTORIA_LOGS_INGESTOR_URL
                            value: "http://{{ .Release.Name }}-victoria-logs-vlinsert:9481/"
                        -   name: VICTORIA_LOGS_QUERIER_URL
                            value: "http://{{ .Release.Name }}-victoria-logs-vlselect:9471/"
                        -   name: DB_TYPE
                            value: "postgres"
                        -   name: DB_HOST
                            value: {{ include "flameHub.postgresql.host" . | quote }}
                        -   name: DB_USERNAME
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "flameHub.postgresql.secretName" . }}
                                    key: username
                        -   name: DB_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "flameHub.postgresql.secretName" . }}
                                    key: password
                        -   name: DB_DATABASE
                            value: "telemetry"
                        -   name: CLIENT_ID
                            value: "system"
                        -   name: CLIENT_SECRET
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "flameHub.effectiveSecretName" .  }}
                                    key: authup-client-secret
                        -   name: REALM
                            value: "master"
                    resources:
                        requests:
                            memory: "512Mi"
                        limits:
                            memory: "2048Mi"
                    startupProbe:
                        httpGet:
                            path: "/"
                            port: 3000
                        periodSeconds: 5
                        failureThreshold: 60
                    readinessProbe:
                        httpGet:
                            path: "/"
                            port: 3000
                        periodSeconds: 5
                        timeoutSeconds: 10
                    livenessProbe:
                        httpGet:
                            path: "/"
                            port: 3000
                        failureThreshold: 3
                        periodSeconds: 15
