{{- if .Values.serverTelemetry.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-flame-hub-server-telemetry-sub-paths
  {{- with .Values.serverTelemetry.ingress.subPathAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
    {{- if .Values.serverTelemetry.ingress.className }}
    ingressClassName: {{ .Values.serverTelemetry.ingress.className }}
    {{- end }}
  rules:
    - host: {{ .Values.serverTelemetry.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.clientUI.ingress.path }}grafana(/|$)(.*)
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ .Release.Name }}-grafana
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Release.Name }}-flame-hub-server-telemetry
    {{- with .Values.serverTelemetry.ingress.annotations }}
    annotations:
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    {{- end }}
spec:
    {{- if .Values.serverTelemetry.ingress.className }}
    ingressClassName: {{ .Values.serverTelemetry.ingress.className }}
    {{- end }}
    rules:
        - host: {{ .Values.serverTelemetry.ingress.hostname }}
          http:
              paths:
                  - path: {{ .Values.serverTelemetry.ingress.path }}
                    pathType: {{ .Values.serverTelemetry.ingress.pathType }}
                    backend:
                        service:
                            name: {{ .Release.Name }}-flame-hub-server-telemetry
                            port:
                                number: 3000
{{- end }}
