global:
    redis:
        # TODO: this should be passed from the flame-hub values.yaml
        password: "start123"

ingress:
    enabled: false
    hostname: ""
    path: "/"
    pathType: "Prefix"

cookieDomain: ""
publicURL: ""
